server:
  port: 8080
  servlet:
    context-path: /basic

spring:
  datasource:
    # 初始化sql 脚本
      url: jdbc:mysql://101.43.7.180:3306/practice?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: ryh123.0
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-timeout: 10000
        idle-timeout: 60000
        max-lifetime: 60000
        maximum-pool-size: 10
        minimum-idle: 5
        pool-name: hikari
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

## mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete    # 表中标记为逻辑删除的字段
      logic-delete-value: 1           # 1 代表删除
      logic-not-delete-value: 0       # 0 代表未删除
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印 sql 语句
    cache-enabled: true               # 默认开启
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-handlers-package: com.ral.young.spring.basic.handler

mybatis-plus-join:
  # 是否打印 mybatis plus join banner 默认true
  banner: true
  # 全局启用副表逻辑删除(默认true) 关闭后关联查询不会加副表逻辑删除
  sub-table-logic: true
  # 拦截器MappedStatement缓存(默认true)
  ms-cache: true
  # 表别名(默认 t)
  table-alias: t
  # 副表逻辑删除条件的位置，支持where、on
  # 默认ON （1.4.7.2及之前版本默认为where）
  logic-del-type: on
  # 非空判断策略
  if-exists: not_blank
