spring:
  banner:
    image:
      location: banner.txt

server:
  port: 8090

scheduled:
  fixedRateTime: 6000
  initialDelayTimeOne: 2000
  initialDelayTimeTwo: 25000
  initialDelayTimeThree: 30000
  initialDelayTimeFour: 35000
