spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${LOG_PATH:./logs/ftp-service}
  level:
    com.ral.young.ftp: INFO

tips: "提示词：##任务：依据所附带的人物照片，人物的标签，指定的输出要求，按照图片红框框出来的人物信息的红色数字编号信息，分别归纳出一句对人物的祝福话语，需体现积极、正面且具有褒义的特点 ##限制：禁止输出含有负面意义的表达 ##人物标签：%s  ##输出要求：按照编号顺序分别输出即可，不要包含其它多余的信息以及特殊字符，按照中文结果输出"