server:
  port: 8080
  servlet:
    context-path: /metrics

minio:
  endpoint: http://192.168.2.20:19000
  access-key: testuser
  secret-key: testuser
  bucket-name: test
  oss:
    bucket-name: oss-bucket
  source:
    bucket-name: source-bucket

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: spring-metrics
  task:
    scheduling:
      pool:
        size: 4
# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  # 将监控指标暴露给 prometheus ，启用导出器
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
